# Generated by Django 4.0.2 on 2022-03-14 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GithubUser',
            fields=[
                ('username', models.CharField(max_length=39, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, null=True)),
                ('bio', models.CharField(max_length=160, null=True)),
                ('blog', models.CharField(max_length=255, null=True)),
                ('company', models.CharField(max_length=255, null=True)),
                ('location', models.CharField(max_length=255, null=True)),
                ('email', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
